### ISSUE TITLE
View glvis -m mesh.000000 -g sol.000000 from web version

### ISSUE THREAD

**Issue by ajithkumarmcw** [GLVis/web#10]
How to view above file from web version or else with https://mybinder.org/v2/gh/GLVis/pyglvis/HEAD?filepath=examples notebook ?

i want view `glvis -m mesh.000000 -g sol.000000` from web version . Is it possible ? https://glvis.org/live/

Or else i want to use web version of jupyter notebook with binder and then see the result of this command `glvis -m mesh.000000 -g sol.000000` . Could you please help me with the jupyter notebook .
I went through the examples notebooks but not able to get this result. I am able to visuvalize only mesh.00000

**Comment by v-dobrev** [comment]
This question is answered here: https://github.com/GLVis/glvis/discussions/207
